'use client'

import React, { useState, useEffect, useRef, useCallback } from 'react'
import { useParams, useSearchParams, useRouter } from 'next/navigation'
import { useSession } from 'next-auth/react'
import { ClipboardList, Sparkles, AlertCircle, CheckCircle, ArrowLeft, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { AITasksAPI, AITask } from '@/lib/api/ai-tasks'
import { useTaskProgress } from '@/lib/hooks/useTaskProgress'
import { useAITaskCache } from '@/lib/hooks/useAITaskCache'
import QuestionnaireResultDisplay from '@/components/features/QuestionnaireResultDisplay'
import { QuestionnaireProgressDisplay } from '@/components/features/QuestionnaireProgressDisplay'
import RerunTaskDialog from '@/components/projects/RerunTaskDialog'
import RollbackButton from '@/components/projects/RollbackButton'
import { TaskAdapter } from '@/lib/adapters/task-adapter'
import type { GenerationResult } from '@/lib/types/ai-generation'
import { Progress } from '@/components/ui/progress'
import { ProfileCompletenessGate } from '@/components/organizations/ProfileCompletenessGate'
import { ProjectQuestionnaireSnapshotResponse, SurveyAPI } from '@/lib/api/survey'

export default function QuestionnairePage() {
  const params = useParams()
  const searchParams = useSearchParams()
  const router = useRouter()
  const { data: session } = useSession()
  const projectId = params.projectId as string
  const matrixTaskId = searchParams?.get('matrixTaskId') || null
  const organizationId = session?.user?.organizationId || ''

  const [currentTask, setCurrentTask] = useState<AITask | null>(null)
  const [generationResult, setGenerationResult] = useState<GenerationResult | null>(null)
  const [clusterStatus, setClusterStatus] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [rerunDialogOpen, setRerunDialogOpen] = useState(false)
  const [showPartialResult, setShowPartialResult] = useState(false)
  const [snapshotInfo, setSnapshotInfo] = useState<ProjectQuestionnaireSnapshotResponse | null>(null)
  const autoGeneratedRef = useRef(false)

  const cache = useAITaskCache()

  const { progress, message: progressMessage, isCompleted, isFailed } = useTaskProgress(currentTask?.id || null)

  function mapSnapshotToGenerationResult(
    snapshot: ProjectQuestionnaireSnapshotResponse,
  ): GenerationResult {
    return {
      id: snapshot.questionnaireTaskId,
      taskId: snapshot.questionnaireTaskId,
      projectId: snapshot.projectId,
      generationType: 'questionnaire',
      selectedResult: {
        questionnaire: snapshot.questions,
        questionnaire_metadata: {
          generatedAt: snapshot.generatedAt,
          snapshotVersion: snapshot.snapshotVersion,
          resolvedControlSetVersion: snapshot.resolvedControlSetVersion,
          questionSetVersion: snapshot.questionSetVersion,
          sourceControlIds: snapshot.sourceControlIds,
          missingQuestionControlIds: snapshot.missingQuestionControlIds,
          total_questions: snapshot.questions.length,
          estimated_time_minutes: Math.max(1, Math.ceil(snapshot.questions.length * 0.5)),
          coverage_map: {},
        },
      },
      selectedModel: 'gpt4',
      confidenceLevel: 'HIGH',
      qualityScores: {
        structural: 100,
        semantic: 100,
        detail: 100,
      },
      consistencyReport: {
        agreements: [],
        disagreements: [],
        highRiskDisagreements: [],
      },
      reviewStatus: 'APPROVED',
      version: snapshot.snapshotVersion,
      createdAt: snapshot.generatedAt,
    }
  }

  const loadLegacyTasks = useCallback(async () => {
    try {
      const cachedQuestionnaire = cache.get(projectId, 'questionnaire')
      if (cachedQuestionnaire) {
        setGenerationResult(cachedQuestionnaire)
      }

      const tasks = await AITasksAPI.getTasksByProject(projectId)
      const questionnaireTasks = tasks.filter(t => t.type === 'questionnaire')
      const questionnaireTask = questionnaireTasks
        .sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())[0]

      if (questionnaireTask) {
        setCurrentTask(questionnaireTask)

        if (questionnaireTask.result) {
          const result = TaskAdapter.toGenerationResult(questionnaireTask)
          setGenerationResult(result)
          cache.set(projectId, 'questionnaire', questionnaireTask.id, result)
        }

        if (questionnaireTask.clusterGenerationStatus) {
          setClusterStatus(questionnaireTask.clusterGenerationStatus)
          const hasPartialResult =
            questionnaireTask.clusterGenerationStatus.completedClusters?.length > 0 &&
            questionnaireTask.clusterGenerationStatus.completedClusters?.length <
              questionnaireTask.clusterGenerationStatus.totalClusters

          if (hasPartialResult && questionnaireTask.result?.questionnaire?.length > 0) {
            setShowPartialResult(true)
          }
        }
      }
    } catch (err: any) {
      console.error('Failed to load tasks:', err)
    }
  }, [projectId, cache])

  const loadExistingQuestionnaire = useCallback(async () => {
    try {
      const snapshot = await SurveyAPI.getProjectQuestionnaireSnapshot(projectId)
      setSnapshotInfo(snapshot)
      setGenerationResult(mapSnapshotToGenerationResult(snapshot))
      setCurrentTask(null)
      setClusterStatus(null)
      setShowPartialResult(false)
      return
    } catch (err: any) {
      if (err?.status !== 404) {
        console.warn('Snapshot lookup failed, falling back to legacy questionnaire flow:', err)
      }
    }

    await loadLegacyTasks()
  }, [loadLegacyTasks, projectId])

  useEffect(() => {
    loadExistingQuestionnaire()
  }, [loadExistingQuestionnaire])

  const handleGenerateLegacyQuestionnaire = useCallback(async (matrixTaskIdParam: string | null) => {
    try {
      setLoading(true)
      setError(null)

      const input: any = {}
      if (matrixTaskIdParam) {
        input.matrixTaskId = matrixTaskIdParam
      }

      const newTask = await AITasksAPI.createTask({
        projectId,
        type: 'questionnaire',
        input,
      })

      setCurrentTask(newTask)
    } catch (err: any) {
      setError(err.message || '生成失败')
      setLoading(false)
    }
  }, [projectId])

  useEffect(() => {
    if (matrixTaskId && !autoGeneratedRef.current && !generationResult && !loading) {
      autoGeneratedRef.current = true
      handleGenerateLegacyQuestionnaire(matrixTaskId)
    }
  }, [matrixTaskId, generationResult, loading, handleGenerateLegacyQuestionnaire])

  const handleGenerate = useCallback(async (regenerate = false) => {
    try {
      setLoading(true)
      setError(null)
      const snapshot = await SurveyAPI.createProjectQuestionnaireSnapshot({
        projectId,
        regenerate,
      })
      setSnapshotInfo(snapshot)
      setGenerationResult(mapSnapshotToGenerationResult(snapshot))
      setCurrentTask(null)
      setClusterStatus(null)
      setShowPartialResult(false)
      setRerunDialogOpen(false)
      setLoading(false)
    } catch (err: any) {
      if (err?.status === 404 || err?.status === 400) {
        setError(err.message || '当前项目无法生成 KG 问卷快照')
        setLoading(false)
        return
      }

      const tasks = await AITasksAPI.getTasksByProject(projectId)
      const matrixTask = tasks
        .filter(t => t.type === 'matrix' && t.status === 'completed')
        .sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())[0]

      if (!matrixTask) {
        setError(err.message || '无法生成 KG 问卷快照，且未找到可回退的矩阵任务')
        setLoading(false)
        return
      }

      await handleGenerateLegacyQuestionnaire(matrixTask.id)
    }
  }, [handleGenerateLegacyQuestionnaire, projectId])

  const loadTaskResult = useCallback(async (taskId: string) => {
    try {
      const task = await AITasksAPI.getTask(taskId)
      if (task.result) {
        const result = TaskAdapter.toGenerationResult(task)
        setGenerationResult(result)
        cache.set(projectId, 'questionnaire', taskId, result)
      }
      if (task.clusterGenerationStatus) {
        setClusterStatus(task.clusterGenerationStatus)
      }
    } catch (err: any) {
      console.error('Failed to load task result:', err)
    }
  }, [projectId, cache])

  useEffect(() => {
    if (isCompleted && currentTask?.id) {
      loadTaskResult(currentTask.id)
      setLoading(false)
    }
  }, [currentTask?.id, isCompleted, loadTaskResult])

  useEffect(() => {
    if (isFailed) {
      setError(progressMessage || '生成失败')
      setLoading(false)
    }
  }, [isFailed, progressMessage])

  const handleRerunComplete = useCallback(() => {
    setCurrentTask(null)
    setGenerationResult(null)
    setClusterStatus(null)
    setRerunDialogOpen(false)
    loadExistingQuestionnaire()
  }, [loadExistingQuestionnaire])

  const pageContent = (
    <div className="w-full px-6 py-8">
      {/* 渐变头部 */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#667eea] to-[#764ba2] p-8 mb-8">
        {/* 装饰性径向渐变 */}
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(255,255,255,0.1)_0%,transparent_50%)]" />

        <div className="relative flex items-start justify-between">
          <div className="flex items-center gap-4">
            {/* 毛玻璃图标背景 */}
            <div className="w-12 h-12 rounded-xl bg-white/20 backdrop-blur-sm flex items-center justify-center">
              <ClipboardList className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white mb-1">问卷生成</h1>
              <p className="text-sm text-white/80">基于成熟度矩阵生成调研问卷</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <RollbackButton
              projectId={projectId}
              taskType="questionnaire"
              taskTypeName="问卷"
              backupExists={!!currentTask?.backupResult}
              onRollbackComplete={handleRerunComplete}
            />
            <Button
              onClick={() => void handleGenerate(true)}
              disabled={!generationResult}
              className="bg-white/10 border border-white/20 text-white hover:bg-white/20 hover:text-white"
            >
              重新生成
            </Button>
            <Button
              variant="outline"
              onClick={() => router.back()}
              className="bg-white/10 border-white/20 text-white hover:bg-white/20 hover:text-white"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              返回
            </Button>
          </div>
        </div>
      </div>

      {error && (
        <Alert variant="destructive" className="mb-6">
          <AlertCircle className="w-4 h-4" />
          <AlertTitle>生成失败</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {/* 聚类进度显示 */}
      {clusterStatus && clusterStatus.totalClusters > 0 && (
        <QuestionnaireProgressDisplay
          taskId={currentTask?.id || ''}
          projectId={projectId}
          clusterStatus={clusterStatus}
        />
      )}

      {/* 部分结果提示 */}
      {showPartialResult && (
        <Alert className="mb-6 bg-amber-50 border-amber-200">
          <div className="flex items-start gap-3">
            <div className="text-amber-600">⚠️</div>
            <div className="flex-1">
              <AlertTitle className="text-amber-800">部分结果可用</AlertTitle>
              <AlertDescription className="text-amber-700">
                已完成 {clusterStatus?.completedClusters?.length || 0} / {clusterStatus?.totalClusters || 0} 个聚类的问卷生成
              </AlertDescription>
            </div>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowPartialResult(false)}
            >
              <X className="w-4 h-4" />
            </Button>
          </div>
        </Alert>
      )}

      {!generationResult && !showPartialResult ? (
        <Card className="border-0 shadow-[0_4px_6px_-1px_rgba(99,102,241,0.1),0_2px_4px_-1px_rgba(99,102,241,0.06)]">
          <CardContent className="py-16 text-center">
            <div className="w-12 h-12 rounded-full bg-gradient-to-br from-indigo-100 to-purple-100 flex items-center justify-center mx-auto mb-4">
              <Sparkles className="w-6 h-6 text-indigo-600" />
            </div>
            <h3 className="text-xl font-semibold text-slate-900 mb-2">还没有生成问卷</h3>
            <p className="text-sm text-slate-500 mb-8">点击下方按钮开始生成问卷</p>

            {loading && progress > 0 ? (
              <div className="max-w-md mx-auto">
                <div className="flex justify-between mb-2">
                  <span className="text-sm text-slate-500">生成进度</span>
                  <span className="text-sm font-semibold text-indigo-600">{progress}%</span>
                </div>
                <Progress value={progress} className="h-3" />
                {progressMessage && (
                  <p className="text-sm text-slate-500 mt-2">{progressMessage}</p>
                )}
              </div>
            ) : (
              <Button
                onClick={() => void handleGenerate()}
                disabled={loading}
                className="bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white px-6 py-3 text-lg"
              >
                <Sparkles className="w-5 h-5 mr-2" />
                {loading ? '生成中...' : '生成问卷'}
              </Button>
            )}
          </CardContent>
        </Card>
      ) : (
        <Card className="border-0 shadow-[0_4px_6px_-1px_rgba(99,102,241,0.1),0_2px_4px_-1px_rgba(99,102,241,0.06)]">
          <CardContent className="p-6">
            <div className="flex items-center gap-3 mb-4 pb-4 border-b border-slate-200">
              <CheckCircle className="w-6 h-6 text-emerald-500" />
              <h3 className="text-xl font-semibold text-slate-900">问卷生成完成</h3>
              {snapshotInfo && (
                <span className="ml-2 text-sm text-indigo-600">
                  (KG 快照 v{snapshotInfo.snapshotVersion}{snapshotInfo.reusedExisting ? ', 复用现有版本' : ''})
                </span>
              )}
              {clusterStatus && clusterStatus.completedClusters?.length < clusterStatus.totalClusters && (
                <span className="ml-2 text-sm text-amber-600">
                  (部分结果: {clusterStatus.completedClusters.length}/{clusterStatus.totalClusters})
                </span>
              )}
            </div>
            {generationResult && <QuestionnaireResultDisplay result={generationResult} />}
          </CardContent>
        </Card>
      )}

      <RerunTaskDialog
        open={rerunDialogOpen && Boolean(currentTask)}
        onClose={() => setRerunDialogOpen(false)}
        projectId={projectId}
        taskType="questionnaire"
        taskTypeName="问卷"
        hasBackup={!!currentTask?.backupResult}
        onRerunComplete={handleRerunComplete}
      />
    </div>
  )

  if (!organizationId) {
    return pageContent
  }

  return (
    <ProfileCompletenessGate
      organizationId={organizationId}
      flowLabel="项目问卷快照生成"
    >
      {pageContent}
    </ProfileCompletenessGate>
  )
}
