'use client'

import React, { useState, useEffect, useRef } from 'react'
import { useParams, useSearchParams } from 'next/navigation'
import { AITasksAPI, AITask } from '@/lib/api/ai-tasks'
import { useTaskProgress } from '@/lib/hooks/useTaskProgress'
import QuestionnaireResultDisplay from '@/components/features/QuestionnaireResultDisplay'
import { QuestionnaireProgressDisplay } from '@/components/features/QuestionnaireProgressDisplay'
import RerunTaskDialog from '@/components/projects/RerunTaskDialog'
import RollbackButton from '@/components/projects/RollbackButton'
import { ClipboardList, Sparkles, AlertCircle, CheckCircle2 } from 'lucide-react'
import { TaskAdapter } from '@/lib/adapters/task-adapter'
import type { GenerationResult } from '@/lib/types/ai-generation'

export default function QuestionnairePage() {
  const params = useParams()
  const searchParams = useSearchParams()
  const projectId = params.projectId as string
  const matrixTaskId = searchParams?.get('matrixTaskId') || null

  const [currentTask, setCurrentTask] = useState<AITask | null>(null)
  const [generationResult, setGenerationResult] = useState<GenerationResult | null>(null)
  const [clusterStatus, setClusterStatus] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [rerunDialogOpen, setRerunDialogOpen] = useState(false)
  const [showPartialResult, setShowPartialResult] = useState(false) // ✅ 是否显示部分结果
  const autoGeneratedRef = useRef(false)

  // 实时进度跟踪
  const { progress, message: progressMessage, isCompleted, isFailed } = useTaskProgress(currentTask?.id || null)

  // 加载现有任务
  useEffect(() => {
    loadExistingTasks()
  }, [projectId])

  // ✅ 当页面加载时，如果URL中有matrixTaskId，自动生成问卷
  useEffect(() => {
    if (matrixTaskId && !autoGeneratedRef.current && !generationResult && !loading) {
      console.log('🎯 检测到matrixTaskId参数，自动生成问卷:', matrixTaskId)
      autoGeneratedRef.current = true
      handleGenerateQuestionnaire(matrixTaskId)
    }
  }, [matrixTaskId, generationResult, loading])

  const loadExistingTasks = async () => {
    try {
      const tasks = await AITasksAPI.getTasksByProject(projectId)
      console.log('📋 加载项目任务:', projectId, '总任务数:', tasks.length)

      // ✅ 先查找最新的问卷任务（包括部分完成的）
      const questionnaireTasks = tasks.filter(t => t.type === 'questionnaire')
      console.log('📋 问卷任务列表:', questionnaireTasks.map(t => ({
        id: t.id,
        status: t.status,
        hasClusterStatus: !!t.clusterGenerationStatus,
        clusterStatus: t.clusterGenerationStatus,
        hasResult: !!t.result,
      })))

      const questionnaireTask = questionnaireTasks
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0]

      if (questionnaireTask) {
        console.log('✅ 找到最新问卷任务:', questionnaireTask.id)
        setCurrentTask(questionnaireTask)

        // ✅ 如果有结果，尝试加载
        if (questionnaireTask.result) {
          const result = TaskAdapter.toGenerationResult(questionnaireTask)
          setGenerationResult(result)
          console.log('✅ 已加载问卷结果')
        }

        // ✅ 如果有聚类状态，加载状态
        if (questionnaireTask.clusterGenerationStatus) {
          setClusterStatus(questionnaireTask.clusterGenerationStatus)
          console.log('✅ 已加载聚类状态:', questionnaireTask.clusterGenerationStatus)

          // ✅ 如果是部分完成，自动显示部分结果
          const hasPartialResult =
            questionnaireTask.clusterGenerationStatus.completedClusters.length > 0 &&
            questionnaireTask.clusterGenerationStatus.completedClusters.length <
              questionnaireTask.clusterGenerationStatus.totalClusters

          if (hasPartialResult && questionnaireTask.result?.questionnaire?.length > 0) {
            setShowPartialResult(true)
          }
        } else {
          console.log('⚠️ 任务没有 clusterGenerationStatus 字段')
        }
      } else {
        console.log('⚠️ 没有找到问卷任务')
      }
    } catch (err: any) {
      console.error('Failed to load tasks:', err)
    }
  }

  const handleGenerate = async () => {
    try {
      const tasks = await AITasksAPI.getTasksByProject(projectId)
      const matrixTask = tasks
        .filter(t => t.type === 'matrix' && t.status === 'completed')
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0]

      if (!matrixTask) {
        alert('请先完成成熟度矩阵生成，然后再生成调研问卷')
        return
      }

      console.log('✅ 找到已完成的矩阵任务:', matrixTask.id)
      handleGenerateQuestionnaire(matrixTask.id)
    } catch (err: any) {
      console.error('Failed to find matrix task:', err)
      setError('无法找到矩阵任务，请先完成成熟度矩阵生成')
    }
  }

  const handleGenerateQuestionnaire = async (matrixTaskIdParam: string | null) => {
    try {
      setLoading(true)
      setError(null)

      const input: any = {}
      if (matrixTaskIdParam) {
        input.matrixTaskId = matrixTaskIdParam
        console.log('📝 创建问卷任务，matrixTaskId:', matrixTaskIdParam)
      }

      const newTask = await AITasksAPI.createTask({
        projectId,
        type: 'questionnaire',
        input,
      })

      console.log('✅ 问卷任务已创建:', newTask.id)
      setCurrentTask(newTask)
      setShowPartialResult(false) // 重置部分结果显示
    } catch (err: any) {
      setError(err.message || '生成失败')
      setLoading(false)
    }
  }

  // 监听任务完成
  useEffect(() => {
    if (isCompleted && currentTask?.id) {
      loadTaskResult(currentTask.id)
      loadClusterStatus(currentTask.id)
      setLoading(false)
    }
  }, [isCompleted])

  // 监听任务失败
  useEffect(() => {
    if (isFailed) {
      setError(progressMessage || '生成失败')
      setLoading(false)
      // ✅ 失败后也尝试加载聚类状态
      if (currentTask?.id) {
        loadClusterStatus(currentTask.id)
      }
    }
  }, [isFailed, progressMessage])

  const loadTaskResult = async (taskId: string) => {
    try {
      const task = await AITasksAPI.getTask(taskId)
      if (task.result) {
        const result = TaskAdapter.toGenerationResult(task)
        setGenerationResult(result)
      }
    } catch (err: any) {
      console.error('Failed to load task result:', err)
    }
  }

  const loadClusterStatus = async (taskId: string) => {
    try {
      const status = await AITasksAPI.getClusterGenerationStatus(taskId)
      setClusterStatus(status)
      console.log('✅ 聚类状态已加载:', status)
    } catch (err: any) {
      console.error('Failed to load cluster status:', err)
    }
  }

  const handleRerunComplete = () => {
    setCurrentTask(null)
    setGenerationResult(null)
    setClusterStatus(null)
    setShowPartialResult(false)
    setRerunDialogOpen(false)
    loadExistingTasks()
  }

  // ✅ 检查是否为部分完成状态
  const isPartiallyCompleted = clusterStatus &&
    clusterStatus.totalClusters > 0 &&
    (clusterStatus.completedClusters.length > 0 ||
     clusterStatus.failedClusters.length > 0) &&
    (clusterStatus.completedClusters.length < clusterStatus.totalClusters ||
      clusterStatus.failedClusters.length > 0)

  // ✅ 检查是否有聚类进度信息（用于显示进度条）
  const hasClusterProgress = clusterStatus &&
    clusterStatus.totalClusters > 0 &&
    (clusterStatus.completedClusters.length > 0 ||
     clusterStatus.failedClusters.length > 0 ||
     clusterStatus.pendingClusters.length > 0)

  // 调试日志
  console.log('🔍 状态检查:', {
    hasClusterStatus: !!clusterStatus,
    totalClusters: clusterStatus?.totalClusters,
    completedCount: clusterStatus?.completedClusters?.length,
    failedCount: clusterStatus?.failedClusters?.length,
    pendingCount: clusterStatus?.pendingClusters?.length,
    isPartiallyCompleted,
    hasClusterProgress,
  })

  return (
    <main className="max-w-[1920px] mx-auto px-6 py-8">
      {/* 头部：标题 + 操作按钮 */}
      <header className="flex items-start justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2 flex items-center gap-3">
            <ClipboardList className="w-8 h-8 text-blue-600" strokeWidth={2} />
            问卷生成
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            基于成熟度矩阵自动生成调研问卷，支持断点续跑
          </p>
        </div>

        <div className="flex items-center gap-3">
          <RollbackButton
            projectId={projectId}
            taskType="questionnaire"
            taskTypeName="问卷"
            backupExists={!!currentTask?.backupResult}
            onRollbackComplete={handleRerunComplete}
          />
          <button
            onClick={() => setRerunDialogOpen(true)}
            disabled={!generationResult}
            className="px-5 py-2.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors min-h-[44px]"
          >
            重新生成
          </button>
        </div>
      </header>

      {/* 错误提示 */}
      {error && (
        <div
          className="mb-6 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg text-red-700 dark:text-red-400 text-sm flex items-start gap-3"
          role="alert"
        >
          <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" strokeWidth={2} />
          <div className="flex-1">
            <p className="font-medium mb-1">生成失败</p>
            <p>{error}</p>
          </div>
          <button
            onClick={() => setError(null)}
            className="flex-shrink-0 text-red-700 dark:text-red-400 hover:text-red-900 dark:hover:text-red-300"
            aria-label="关闭错误提示"
          >
            ×
          </button>
        </div>
      )}

      {/* ✅ 显示聚类进度（如果有进度信息） */}
      {hasClusterProgress && clusterStatus && (
        <div className="mb-6">
          <QuestionnaireProgressDisplay
            taskId={currentTask!.id}
            projectId={projectId}
            clusterStatus={clusterStatus}
            onResumeComplete={handleRerunComplete}
            onRegenerateComplete={handleRerunComplete}
          />

          {/* 切换显示部分结果 */}
          {generationResult && generationResult.selectedResult?.questionnaire && (
            <div className="mt-6 text-center">
              <button
                onClick={() => setShowPartialResult(!showPartialResult)}
                className="px-4 py-2 text-sm font-medium text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 transition-colors"
              >
                {showPartialResult ? '隐藏' : '查看'}已生成的题目 ({generationResult.selectedResult.questionnaire.length} 题)
              </button>
            </div>
          )}
        </div>
      )}

      {/* 内容区域 */}
      {!generationResult ? (
        <section className="text-center py-16 px-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
          <div className="flex justify-center mb-6">
            <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-full">
              <Sparkles className="w-12 h-12 text-blue-500" strokeWidth={2} />
            </div>
          </div>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
            还没有生成问卷
          </h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">
            点击下方按钮开始生成调研问卷
          </p>

          {loading && progress > 0 ? (
            <div className="max-w-md mx-auto">
              <div className="mb-4 flex items-center justify-between text-sm">
                <span className="text-gray-600 dark:text-gray-400">生成进度</span>
                <span className="font-medium text-blue-600 dark:text-blue-400">{progress}%</span>
              </div>
              <div className="w-full h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden mb-3">
                <div
                  className="h-full bg-gradient-to-r from-blue-500 to-blue-600 transition-all duration-300"
                  style={{ width: `${progress}%` }}
                />
              </div>
              {progressMessage && (
                <p className="text-sm text-gray-500 dark:text-gray-400">{progressMessage}</p>
              )}
            </div>
          ) : (
            <button
              onClick={handleGenerate}
              disabled={loading}
              className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg shadow-sm hover:shadow transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed min-h-[48px]"
            >
              {loading ? (
                <>
                  <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  生成中...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" strokeWidth={2} />
                  生成问卷
                </>
              )}
            </button>
          )}
        </section>
      ) : showPartialResult || !isPartiallyCompleted ? (
        <section className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center gap-2 mb-6 pb-4 border-b border-gray-200 dark:border-gray-700">
            <CheckCircle2 className="w-6 h-6 text-green-500" strokeWidth={2} />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              {isPartiallyCompleted ? '问卷部分完成' : '问卷生成完成'}
            </h2>
            {hasClusterProgress && (
              <span className="ml-2 px-2 py-1 text-xs font-medium bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200 rounded">
                {clusterStatus?.completedClusters.length || 0} / {clusterStatus?.totalClusters || 0} 聚类已完成
              </span>
            )}
          </div>
          <QuestionnaireResultDisplay result={generationResult} />
        </section>
      ) : null}

      {/* 重新生成对话框 */}
      <RerunTaskDialog
        open={rerunDialogOpen}
        onClose={() => setRerunDialogOpen(false)}
        projectId={projectId}
        taskType="questionnaire"
        taskTypeName="问卷"
        hasBackup={!!currentTask?.backupResult}
        onRerunComplete={handleRerunComplete}
      />
    </main>
  )
}
