'use client'

import React, { useState, useEffect, useCallback } from 'react'
import { useParams, useSearchParams } from 'next/navigation'
import { AITasksAPI, AITask } from '@/lib/api/ai-tasks'
import { useTaskProgress } from '@/lib/hooks/useTaskProgress'
import { useAITaskCache } from '@/lib/hooks/useAITaskCache'
import MatrixResultDisplay from '@/components/features/MatrixResultDisplay'
import RerunTaskDialog from '@/components/projects/RerunTaskDialog'
import RollbackButton from '@/components/projects/RollbackButton'
import { Grid3x3, Sparkles, AlertCircle, CheckCircle2 } from 'lucide-react'
import { TaskAdapter } from '@/lib/adapters/task-adapter'
import type { GenerationResult } from '@/lib/types/ai-generation'

export default function MatrixPage() {
  const params = useParams()
  const searchParams = useSearchParams()
  const projectId = params.projectId as string
  const clusteringTaskId = searchParams?.get('clusteringTaskId') || null

  const [currentTask, setCurrentTask] = useState<AITask | null>(null)
  const [generationResult, setGenerationResult] = useState<GenerationResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [rerunDialogOpen, setRerunDialogOpen] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false) // 标记是否已自动触发生成

  // 添加缓存Hook
  const cache = useAITaskCache()

  const { progress, message: progressMessage, isCompleted, isFailed } = useTaskProgress(currentTask?.id || null)

  useEffect(() => {
    loadExistingTasks()
  }, [projectId])

  // ✅ 当页面加载时，如果URL中有clusteringTaskId，自动生成矩阵
  useEffect(() => {
    if (clusteringTaskId && !autoGenerated && !generationResult && !loading) {
      console.log('🎯 检测到clusteringTaskId参数，自动生成矩阵:', clusteringTaskId)
      // ✅ 立即标记为已生成，防止重复触发
      setAutoGenerated(true)
      handleGenerateMatrix(clusteringTaskId)
    }
  }, [clusteringTaskId, autoGenerated, generationResult, loading])

  const loadExistingTasks = useCallback(async () => {
    try {
      // 尝试从缓存加载
      const cachedMatrix = cache.get(projectId, 'matrix')
      if (cachedMatrix) {
        console.log('✅ 从缓存加载成熟度矩阵结果')
        setGenerationResult(cachedMatrix)
      }

      const tasks = await AITasksAPI.getTasksByProject(projectId)
      // ✅ 先筛选已完成的任务，再按时间排序
      const matrixTask = tasks
        .filter(t => t.type === 'matrix' && t.status === 'completed')
        .sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())[0]

      if (matrixTask && matrixTask.result) {
        setCurrentTask(matrixTask)
        const result = TaskAdapter.toGenerationResult(matrixTask)
        setGenerationResult(result)

        // 缓存结果
        cache.set(projectId, 'matrix', matrixTask.id, result)
      }
    } catch (err: any) {
      console.error('Failed to load tasks:', err)
    }
  }, [projectId, cache])

  const handleGenerate = useCallback(async () => {
    // ✅ 手动生成时，查找项目中已完成的聚类任务
    try {
      const tasks = await AITasksAPI.getTasksByProject(projectId)
      const clusteringTask = tasks
        .filter(t => t.type === 'clustering' && t.status === 'completed')
        .sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())[0]

      if (!clusteringTask) {
        alert('请先完成聚类分析，然后再生成成熟度矩阵')
        return
      }

      console.log('✅ 找到已完成的聚类任务:', clusteringTask.id)
      handleGenerateMatrix(clusteringTask.id)
    } catch (err: any) {
      console.error('Failed to find clustering task:', err)
      setError('无法找到聚类任务，请先完成聚类分析')
    }
  }, [projectId])

  const handleGenerateMatrix = useCallback(async (clusteringTaskIdParam: string | null) => {
    try {
      setLoading(true)
      setError(null)

      // ✅ 如果提供了clusteringTaskId，传递给后端
      const input: any = {}
      if (clusteringTaskIdParam) {
        input.clusteringTaskId = clusteringTaskIdParam
        console.log('📝 创建矩阵任务，clusteringTaskId:', clusteringTaskIdParam)
      }

      const newTask = await AITasksAPI.createTask({
        projectId,
        type: 'matrix', // ✅ 改为小写，匹配数据库枚举
        input,
      })

      console.log('✅ 矩阵任务已创建:', newTask.id)
      setCurrentTask(newTask)
    } catch (err: any) {
      setError(err.message || '生成失败')
      setLoading(false)
    }
  }, [projectId])

  useEffect(() => {
    if (isCompleted && currentTask?.id) {
      loadTaskResult(currentTask.id)
      setLoading(false)
    }
  }, [isCompleted])

  useEffect(() => {
    if (isFailed) {
      setError(progressMessage || '生成失败')
      setLoading(false)
    }
  }, [isFailed, progressMessage])

  const loadTaskResult = useCallback(async (taskId: string) => {
    try {
      const task = await AITasksAPI.getTask(taskId)
      if (task.result) {
        const result = TaskAdapter.toGenerationResult(task)
        setGenerationResult(result)

        // 缓存结果
        cache.set(projectId, 'matrix', taskId, result)
      }
    } catch (err: any) {
      console.error('Failed to load task result:', err)
    }
  }, [projectId, cache])

  const handleRerunComplete = useCallback(() => {
    setCurrentTask(null)
    setGenerationResult(null)
    setRerunDialogOpen(false)
    loadExistingTasks()
  }, [loadExistingTasks])

  return (
    <main className="max-w-[1920px] mx-auto px-6 py-8">
      <header className="flex items-start justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2 flex items-center gap-3">
            <Grid3x3 className="w-8 h-8 text-blue-600" strokeWidth={2} />
            成熟度矩阵
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            生成成熟度评估矩阵，可视化展示合规成熟度水平
          </p>
        </div>

        <div className="flex items-center gap-3">
          <RollbackButton
            projectId={projectId}
            taskType="matrix"
            taskTypeName="成熟度矩阵"
            backupExists={!!currentTask?.backupResult}
            onRollbackComplete={handleRerunComplete}
          />
          <button
            onClick={() => setRerunDialogOpen(true)}
            disabled={!generationResult}
            className="px-5 py-2.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors min-h-[44px]"
          >
            重新生成
          </button>
        </div>
      </header>

      {error && (
        <div className="mb-6 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg text-red-700 dark:text-red-400 text-sm flex items-start gap-3">
          <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" strokeWidth={2} />
          <div className="flex-1">
            <p className="font-medium mb-1">生成失败</p>
            <p>{error}</p>
          </div>
        </div>
      )}

      {!generationResult ? (
        <section className="text-center py-16 px-6 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700">
          <div className="flex justify-center mb-6">
            <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-full">
              <Sparkles className="w-12 h-12 text-blue-500" strokeWidth={2} />
            </div>
          </div>
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
            还没有生成成熟度矩阵
          </h2>
          <p className="text-gray-500 dark:text-gray-400 mb-8">
            点击下方按钮开始生成成熟度矩阵
          </p>

          {loading && progress > 0 ? (
            <div className="max-w-md mx-auto">
              <div className="mb-4 flex items-center justify-between text-sm">
                <span className="text-gray-600 dark:text-gray-400">生成进度</span>
                <span className="font-medium text-blue-600 dark:text-blue-400">{progress}%</span>
              </div>
              <div className="w-full h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden mb-3">
                <div className="h-full bg-gradient-to-r from-blue-500 to-blue-600 transition-all duration-300" style={{ width: `${progress}%` }} />
              </div>
              {progressMessage && <p className="text-sm text-gray-500 dark:text-gray-400">{progressMessage}</p>}
            </div>
          ) : (
            <button
              onClick={handleGenerate}
              disabled={loading}
              className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg shadow-sm hover:shadow transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed min-h-[48px]"
            >
              {loading ? (
                <>
                  <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  生成中...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" strokeWidth={2} />
                  生成矩阵
                </>
              )}
            </button>
          )}
        </section>
      ) : (
        <section className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center gap-2 mb-6 pb-4 border-b border-gray-200 dark:border-gray-700">
            <CheckCircle2 className="w-6 h-6 text-green-500" strokeWidth={2} />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">矩阵生成完成</h2>
          </div>
          <MatrixResultDisplay result={generationResult} />
        </section>
      )}

      <RerunTaskDialog
        open={rerunDialogOpen}
        onClose={() => setRerunDialogOpen(false)}
        projectId={projectId}
        taskType="matrix"
        taskTypeName="成熟度矩阵"
        hasBackup={!!currentTask?.backupResult}
        onRerunComplete={handleRerunComplete}
      />
    </main>
  )
}
