import { ThinkTankEventName } from './thinktank-event-contract'

export const THINKTANK_GOVERNANCE_EVENT_NAMES = [
  ThinkTankEventName.AccessOpened,
  ThinkTankEventName.AccessDenied,
  ThinkTankEventName.ModuleEnabled,
  ThinkTankEventName.ModuleDisabled,
  ThinkTankEventName.RoleAccessUpdated,
  ThinkTankEventName.WorkflowStarted,
  ThinkTankEventName.WorkflowStartFailed,
  ThinkTankEventName.WorkflowCompleted,
  ThinkTankEventName.QuickConsultStarted,
  ThinkTankEventName.QuickConsultCompleted,
  ThinkTankEventName.QuickConsultFailed,
  ThinkTankEventName.MethodBrowseFailed,
  ThinkTankEventName.OutputExported,
  ThinkTankEventName.SessionDeleted,
  ThinkTankEventName.OutputDeleted,
  ThinkTankEventName.ProviderCallCompleted,
  ThinkTankEventName.ProviderCallFailed,
  ThinkTankEventName.ProviderCallRetried,
  ThinkTankEventName.PromptCacheHit,
  ThinkTankEventName.PromptCacheMiss,
  ThinkTankEventName.CheckpointPersistenceFailed,
  ThinkTankEventName.RecommendationFeedbackSubmitted,
  ThinkTankEventName.OutputRatingSubmitted,
  ThinkTankEventName.OutputFavoriteUpdated,
  ThinkTankEventName.OutputKnowledgeBaseAssociationRequested,
  ThinkTankEventName.OutputKnowledgeBaseAssociationUpdated,
  ThinkTankEventName.ContextCompressionExecuted,
  ThinkTankEventName.ContextCompressionDeferred,
  ThinkTankEventName.PartyModeBudgetExceeded,
  ThinkTankEventName.PartyModeAdvisorFailed,
] as const
